import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
