format = """
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$character\
"""

right_format = """
$cmd_duration\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$time\
"""

add_newline = true

[character]
format = "$symbol "
success_symbol = "[◉](bold italic bright-yellow)"
error_symbol = "[⊘](italic purple)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "italic bright-purple"
symbol = "◇┈"
disabled = false

[username]
style_user = "yellow bold"
style_root = "purple bold italic"
format = "[$user]($style) ▻ "
disabled = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "▦ "
read_only = " ■"
style = "italic blue"
format = ' [$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
min_time = 500
format = "[ ~$duration ](italic dimmed white)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style)"
symbol = "[◬](bold bright-blue)"
style = "bold italic bright-blue"

[git_status]
style = "italic bright-blue"
format = """([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▲│[${count}](bold white)│](italic green)"
behind = "[▽│[${count}](bold white)│](italic red)"
diverged = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◦◫◦](italic white)"
modified = "[●◦](italic yellow)"
staged = "[■┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

