unbind r
bind r source-file ~/.tmux.conf; display-message "tmux config reloaded!"

set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',xterm-256color:RGB'

set-option -g default-shell /bin/zsh

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'resize-pane -L 1'
bind -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'resize-pane -D 1'
bind -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'resize-pane -U 1'
bind -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'resize-pane -R 1'

bind-key -T copy-mode-vi M-h resize-pane -L 1
bind-key -T copy-mode-vi M-j resize-pane -D 1
bind-key -T copy-mode-vi M-k resize-pane -U 1
bind-key -T copy-mode-vi M-l resize-pane -R 1

bind '"' split-window -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

bind '\' set status
if-shell "[[ $(tmux lsw | wc -l) -le 1]]]" 'set -g status'

set -g status on
set-option -g status-position top
set -g status-interval 1

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set-option -g focus-events on
set-option -sg escape-time 0

set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disable_color_option '0'
set -g status-justify absolute-centre

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 's'

set -g @rose_pine_variant 'main'
set -g @rose_pine_directory 'on'
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_date_time '%a | %d/%m/%Y'
set -g @rose_pine_status_left_prepend_section '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g @rose_pine_status_right_append_section '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'

run '~/.tmux/plugins/tpm/tpm'
set -g status-left-length 100
set -g status-right-length 100
